# Generated by Django 2.2.28 on 2022-06-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(help_text='This demonstrates the wrapper adding an "add" button only', on_delete=django.db.models.deletion.CASCADE, related_name='current_players', to='testapp.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='future_team',
            field=models.ForeignKey(help_text='This demonstrates the wrapper adding both an "add" and an "edit" button', on_delete=django.db.models.deletion.CASCADE, related_name='future_players', to='testapp.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_teams',
            field=models.ManyToManyField(help_text='This demonstrates the wrapper on a ManyToMany field', related_name='ancient_players', to='testapp.Team'),
        ),
    ]
